close all
clear
clc

% Load data
load('testInputData_MSCKF_step.mat')
%%% TODO: resave struct (contains GTSAM objects!)

% Call bus definition generator
charOutputFolder    = "./bus_defs_MSCKF";

% Assemble inputs as a struct array
strBusDefs = struct(...
    'Name',       { "strMeasBus", "strMeasModelParams", "strDynParams", "strFilterMutabConfig" }, ...
    'Description', { ...
        "Struct containing measurement data and flags.", ...
        "Struct containing buffers and parameters for measurement models of the Observation update step.", ...
        "Struct containing parameters required by the Time update step.", ...
        "Struct containing mutable configuration parameters for the filter." }, ...
    'Value',      { strMeasBus, strMeasModelParams, strDynParams, strFilterMutabConfig });

for idBus = 1:numel(strBusDefs)
    charBusName      = strBusDefs(idBus).Name;
    charTestDescript = strBusDefs(idBus).Description;
    strInput         = strBusDefs(idBus).Value;

    GenerateBusDefinitionFile(strInput, ...
        charBusName, ...
        charOutputFolder, ...
        "bStoreDefaultValues", true, ...
        "bDefineBusesInPlace", true, ...
        "charHeaderDescription", charTestDescript);
end
