classdef CAutoGenICD < handle
    %% DESCRIPTION
    % CAutoGenICD class automatically generates ICDs for Simulink subsystems. Loads a model, runs an init 
    % script, compiles the model, extracts I/O data for specified subsystems, and generates. 
    % Excel ICD files with standardized naming conventions.
    % -------------------------------------------------------------------------------------------------------------
    %% CHANGELOG
    % 15-05-2025    Pietro Califano & o4-mini-high    First prototype implementation.
    % -------------------------------------------------------------------------------------------------------------
    %% METHODS
    % See methods()
    % -------------------------------------------------------------------------------------------------------------
    %% PROPERTIES
    % See properties()
    % -------------------------------------------------------------------------------------------------------------
    %% DEPENDENCIES
    % Simulink Report toolbox.
    % -------------------------------------------------------------------------------------------------------------
    %% TODO
    % [-]
    % -------------------------------------------------------------------------------------------------------------

    properties
        charModelName       % SLX model file or model name (char)
        cellSubsystemPaths  % Cell array of subsystem paths (cell)
        charInitScript      % Initialization script path (char)
        strICDData          % Struct of extracted ICD tables (struct)
    end

    methods (Access = public)
        % CONSTRUCTOR
        function self = CAutoGenICD(charModelPath, cellSubsystemPaths, charInitScript)
            arguments
                charModelPath      (1,1) string {mustBeA(charModelPath, ["string", "char"])}
                cellSubsystemPaths {iscell}
                charInitScript     (1,1) string {mustBeA(charInitScript, ["string", "char"])}
            end

            % Assert model and init scripts exist
            if isfile(charModelPath)
                error('Model file %s not found!', charModelPath);
            end
            if isfile(charInitScript)
                error('Initialization script %s not found!', charInitScript);
            end

            if isempty(cellSubsystemPaths)
                warning('No subsystem specified. You should specify at least one subsystem to generate an interface control document.')
            end

            % Store model, subsystems, and init script
            self.charModelName      = charModelPath;
            self.cellSubsystemPaths = cellSubsystemPaths;
            self.charInitScript     = charInitScript;

            % Initialize ICDData
            self.strICDData = struct();
        end

        % PUBLIC METHODS
        function getICDDataFromModel(self)
            % Compile model and extract ICD data for each subsystem
            self.compileModel_();

            strData = struct();

            for dIdx = 1:numel(self.cellSubsystemPaths)

                % Get path to subsystem
                charSubsysPath = self.cellSubsystemPaths{dIdx};
                % Get valid name of subsystem to name field
                charKey = matlab.lang.makeValidName(strrep(charSubsysPath, '/', '_'));

                % Get data from SLX model
                if contains(struct2array(ver), 'Simulink Report Generator')
                    strData.(charKey) = self.extractSubsysData_(charSubsysPath);
                else
                    strData.(charKey) = self.extractSubsysDataManual_(charSubsysPath);
                end
            end

            % Assign data for each subsystem
            self.strICDData = strData;
        end

        function exportICD(self, charOutputFolder, kwargs)
            arguments
                self
                charOutputFolder (1,1) string {mustBeA(charOutputFolder, ["string", "char"])} = "./autogenerated_ICD"
            end
            arguments
                kwargs.enumOutFormat (1,1) string {mustBeMember(kwargs.enumOutFormat, ["xslx", "csv", "dat", "xml"])} = "csv"
            end
            % Method to build and export ICD file for each subsystem in strICDData

            if isempty(fieldnames(self.strICDData))
                self.getICDDataFromModel();
            end

            if ~exist(charOutputFolder, 'dir')
                mkdir(charOutputFolder);
            end

            % Determine format type
            if strcmpi(kwargs.enumOutFormat, "xslx")
                charFormatType = "spreadsheet";
            elseif strcmpi(kwargs.enumOutFormat, "xml")
                charFormatType = "xml";
            else
                charFormatType = "text";
            end

            % Get keys of ICD datastruct
            cellKeys = fieldnames(self.strICDData);
    
            % For each datastruct, write a document
            for dIdx = 1:numel(cellKeys)
    
                % Collect formatted data
                charKey = cellKeys{dIdx};
                tableICD = self.strICDData.(charKey);
                
                % Write table
                charFilename = fullfile( charOutputFolder, strcat(charKey, '_ICD.', kwargs.enumOutFormat) );
                writetable(tableICD, charFilename, ...
                            'Delimiter',',', ...
                            "FileType", charFormatType, ...
                            'Sheet', 1, ...
                            'WriteVariableNames', true, ...
                            "WriteRowNames",true, ...
                            "AutoFitWidth", true, ...
                            'PreserveFormat',true);
                
                fprintf('Generated ICD for "%s" system to file "%s"\n', charKey, charFilename);
            end

        end
    end

    % PROTECTED METHODS
    methods (Access = protected)
        function compileModel_(self)

            % Run init script, load and compile the model
            run(self.charInitScript);

            % Load system
            load_system(self.charModelName);

            % Build simulink model
            % slbuild(self.charModelName); % DEVNOTE: this builds the model
            set_param(self.charModelName, 'SimulationCommand', 'update');
        end

        function tableICD = extractSubsysData_(self, charSubsysPath)
            arguments (Input)
                self
                charSubsysPath (1,:) char
            end
            arguments (Output)
                tableICD table
            end

            % Use SystemIO reporter for summary
            import slreportgen.report.SystemIO

            objSysIO = SystemIO(charSubsysPath);

            % Compile this subsystem
            set_param(bdroot(charSubsysPath), 'SimulationCommand', 'update');

            % Fetch input/output summary tables
            tableIn  = objSysIO.getInputSummaryTable();
            tableOut = objSysIO.getOutputSummaryTable();

            % Combine and ensure Description column
            tableICD = [tableIn; tableOut];

            % Add empty description if not present
            if ~ismember('Description', tableICD.Properties.VariableNames)
                tableICD.Description = repmat({''}, height(tableICD), 1);
            end

            % Select and rename columns
            tableICD = tableICD(:, {'Name', 'Dimensions', 'DataType', 'Description'});
            tableICD.Properties.VariableNames = {'Signal Name', 'Dimension', 'Data Type', 'Description'};

            % Prepare additional columns
            dNum = height(tableICD);
            cellTelemetry       = false(dNum, 1);
            cellInitialization  = false(dNum, 1);
            cellNotes           = repmat({''}, dNum, 1);

            % Retrieve port handles
            handlesIn  = objSysIO.InputPortHandles;
            handlesOut = objSysIO.OutputPortHandles;
            handlesAll = [handlesIn; handlesOut];

            % Loop each signal
            for i = 1:dNum

                tmpHandle = handlesAll(i);
                
                % Telemetry flag
                cellTelemetry(i) = strcmp(get_param(tmpHandle, 'DataLogging'), 'on');

                % Initialization for outports
                if ismember(tmpHandle, handlesOut)
                    blkHandle = get_param(tmpHandle, 'DstBlockHandle');
                    valInit = get_param(blkHandle, 'InitialOutput');
                    cellInitialization(i) = ~(isempty(valInit) || strcmp(valInit, '0'));
                else
                    cellInitialization(i) = true;
                end

                % Notes from block
                try
                    blkPath = getfullname(get_param(tmpHandle, 'DstBlockHandle'));
                    cellNotes{i} = get_param(blkPath, 'Notes');
                catch
                    cellNotes{i} = '';
                end
            end

            % Append to table
            tableICD.Telemetry      = cellTelemetry;
            tableICD.Initialization = cellInitialization;
            tableICD.Notes          = cellNotes;
        end

        % Manual method if Simulink Report Generator is not available
        function tableICD = extractSubsysDataManual_(self, charSubsysPath)
            % Extract I/O data for one subsystem:
            % [Signal Name, Dimension, Data Type, Telemetry,
            %  Initialization, Description, Notes]

            % Compile model data for this subsystem
            charBDRoot = bdroot(charSubsysPath);
            self.compileModel_(charBDRoot);

            % Find inport/outport blocks
            cellInPorts  = find_system(charSubsysPath, 'SearchDepth', 1, 'BlockType', 'Inport');
            cellOutPorts = find_system(charSubsysPath, 'SearchDepth', 1, 'BlockType', 'Outport');
            cellAllPorts = [cellInPorts; cellOutPorts];
            dNumPorts    = numel(cellAllPorts);

            % Preallocate rows
            cellRows = cell(dNumPorts, 7);
            objModelWorkspace = get_param(charBDRoot, 'ModelWorkspace');
            dRow = 0;

            for dPortIdx = 1:dNumPorts

                charBlkPath = cellAllPorts{dPortIdx};
                strPortHandles = get_param(charBlkPath, 'PortHandles');
                charBlkType = get_param(charBlkPath, 'BlockType');

                if strcmp(charBlkType, 'Inport')
                    dLineHandle = get_param(strPortHandles.Outport, 'Line');
                else
                    dLineHandle = get_param(strPortHandles.Inport, 'Line');
                end

                dRow = dRow + 1;
                
                % GEt and store data
                % 1) Signal Name
                charSignalName = get_param(dLineHandle, 'Name');
                if isempty(charSignalName), charSignalName = '<unnamed>'; end
                cellRows{dRow,1} = charSignalName;

                % 2) Dimension
                dDims = get_param(dLineHandle, 'CompiledPortDimensions');
                charDimension = mat2str(dDims);
                cellRows{dRow,2} = charDimension;

                % 3) Data Type
                charDataType = get_param(dLineHandle, 'CompiledPortDataType');
                cellRows{dRow,3} = charDataType;

                % 4) Telemetry
                charDataLogging = get_param(dLineHandle, 'DataLogging');
                bTelemetry = strcmp(charDataLogging, 'on');
                cellRows{dRow,4} = bTelemetry;

                % 5) Initialization
                if strcmp(charBlkType, 'Outport')
                    charInitVal = get_param(charBlkPath, 'InitialOutput');
                    bInitialization = ~(isempty(charInitVal) || strcmp(charInitVal, '0'));
                else
                    bInitialization = true;
                end
                cellRows{dRow,5} = bInitialization;

                % 6) Description (prefer Simulink.Signal object)
                charDescription = '';
                try
                    objSignal = objModelWorkspace.getVariable(charSignalName);
                    if isa(objSignal, 'Simulink.Signal')
                        charDescription = objSignal.Description;
                    end
                catch
                    % No matching signal object
                end

                if isempty(charDescription)
                    charDescription = get_param(charBlkPath, 'Description');
                end
                
                cellRows{dRow,6} = charDescription;

                % 7) Notes
                try
                    charNotes = get_param(charBlkPath, 'Notes');
                catch
                    charNotes = '';
                end
                cellRows{dRow,7} = charNotes;
            end

            % Build table and set column names
            % DEVNOTE: this define the template for the output file. You should change it if another
            % template is required.
            tableICD = cell2table(cellRows, ...
                'VariableNames', {'SignalName','Dimension','DataType', ...
                'Telemetry','Initialization','Description','Notes'});

            % Rename for Excel headers
            tableICD.Properties.VariableNames = { ...
                'Signal Name','Dimension','Data Type', ...
                'Telemetry','Initialization','Description','Notes'};
        end
    end
end
